---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prime-video-app
  labels:
    app: prime-video-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prime-video-app
  template:
    metadata:
      labels:
        app: prime-video-app
    spec:
      containers:
      - name: prime-video-app-container
        image: "${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/amazon-prime:latest"
        ports:
        - containerPort: 3000
        env:
          - name: AWS_ACCOUNT_ID
            valueFrom:
              secretKeyRef:
                name: aws-account-secret
                key: account-id