apiVersion: v1
kind: Service
metadata:
  name: prime-video-app-serv
spec:
  selector:
    app: prime-video-app
  ports:
  - port: 3000
    name: http
    protocol: TCP
    targetPort: 3000
  type: LoadBalancer
